import type { Metadata } from "next";
import { Providers } from "@/shared/lib/query-provider";
import "./globals.css";

import Header from "@/shared/ui/Header";

export const metadata: Metadata = {
  title: "Books App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`h-full antialiased`}>
      <body>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
